export const LOAD = 'LOAD'
export const END = 'END'

export const LOADSAVE = 'LOADSAVE'
export const ENDSAVE = 'ENDSAVE'

export const LOAD_ERROR = 'LOAD_ERROR'
export const CARGAR_INFO_GENERAL = 'CARGAR_INFO_GENERAL'
export const CARGAR_INFO_GENERAL_EXITO = 'CARGAR_INFO_GENERAL_EXITO'
export const CARGAR_INFO_GENERAL_ERROR = 'CARGAR_INFO_GENERAL_ERROR'
export const AGREGAR_FOTO = 'AGREGAR_FOTO'

export const CARGAR_INFO_CONTACTO = 'CARGAR_INFO_CONTACTO'
export const GUARDAR_INFO_CONTACTO = 'GUARDAR_INFO_CONTACTO'

export const INIT_SAVE_CONTACT = 'INIT_SAVE_CONTACT'
export const SAVE_CONTACT_ERROR = 'SAVE_CONTACT_ERROR'
export const SAVE_CONTACT_EXITO = 'SAVE_CONTACT_EXITO'

export const OBTENER_PAISES = 'OBTENER_PAISES'
export const OBTENER_ESTADO_CIVIL = 'OBTENER_ESTADO_CIVIL'
export const OBTENER_TIPO_DOC = 'OBTENER_TIPO_DOC'
export const OBTENER_UBIGEO = 'OBTENER_UBIGEO'
export const OBTENER_EVALUADOR_EVALUADO = 'OBTENER_EVALUADOR_EVALUADO'

export const OBTENER_INSTITUCION = 'OBTENER_INSTITUCION'
export const OBTENER_INDUSTRIA = 'OBTENER_INDUSTRIA'
export const OBTENER_AREA_PUESTO = 'OBTENER_AREA_PUESTO'
export const OBTENER_TIPO_DEDICACION_DOCENTE = 'OBTENER_TIPO_DEDICACION_DOCENTE'
export const OBTENER_EXPERIENCIA_LABORAL = 'OBTENER_EXPERIENCIA_LABORAL'
export const OBTENER_CLASIFICACION_CARRERA = 'OBTENER_CLASIFICACION_CARRERA'
export const OBTENER_NIVEL_ACADEMICO = 'OBTENER_NIVEL_ACADEMICO'
export const OBTENER_ESTADO_ESTUDIO = 'OBTENER_ESTADO_ESTUDIO'
export const OBTENER_ESTUDIO = 'OBTENER_ESTUDIO'
export const OBTENER_PERSONA_CONOCIMIENTO = 'OBTENER_PERSONA_CONOCIMIENTO'
export const OBTENER_IDIOMAS = 'OBTENER_IDIOMAS'
export const OBTENER_PERSONA_IDIOMAS = 'OBTENER_PERSONA_IDIOMAS'
export const OBTENER_REFERENCIA_LABORAL = 'OBTENER_REFERENCIA_LABORAL'
export const OBTENER_TIPO_ADJUNTO = 'OBTENER_TIPO_ADJUNTO'

export const SAVE_PERSONA = 'SAVE_PERSONA'
export const SAVE_PERSONA_ERROR = 'SAVE_PERSONA_ERROR'

export const SAVE_EXPERIENCIA_LABORAL = 'SAVE_EXPERIENCIA_LABORAL'
export const EDIT_EXPERIENCIA_LABORAL = 'EDIT_EXPERIENCIA_LABORAL'
export const SAVE_EXPERIENCIA_LABORAL_ERROR = 'SAVE_EXPERIENCIA_LABORAL_ERROR'

export const LOAD_ESTUDIOS = 'LOAD_ESTUDIOS'
export const OBTENER_ESTUDIOS = 'OBTENER_ESTUDIOS'
export const SAVE_ESTUDIO = 'SAVE_ESTUDIO'
export const END_SAVE = 'END_SAVE'
export const SAVE_ESTUDIO_ERROR = 'SAVE_ESTUDIO_ERROR'

export const SAVE_PERSONA_CONOCIMIENTO = 'SAVE_PERSONA_CONOCIMIENTO'
export const SAVE_PERSONA_CONOCIMIENTO_ERROR = 'SAVE_PERSONA_CONOCIMIENTO_ERROR'

export const SAVE_PERSONA_IDIOMA = 'SAVE_PERSONA_IDIOMA'
export const SAVE_PERSONA_IDIOMA_ERROR = 'SAVE_PERSONA_IDIOMA_ERROR'

export const SAVE_REFERENCIA_LABORAL = 'SAVE_REFERENCIA_LABORAL'
export const SAVE_REFERENCIA_LABORAL_ERROR = 'SAVE_REFERENCIA_LABORAL_ERROR'

export const SAVE_PERSONA_ADJUNTO = 'SAVE_PERSONA_ADJUNTO'
export const SAVE_PERSONA_ADJUNTO_ERROR = 'SAVE_PERSONA_ADJUNTO_ERROR'

export const CONFIRMACION_GUARDAR = 'CONFIRMACION_GUARDAR'
export const CONFIRMACION_GUARDAR_ERROR = 'CONFIRMACION_GUARDAR_ERROR'

export const OBTENER_INSTITUCION_PAIS = 'OBTENER_INSTITUCION_PAIS'
export const OBTENER_INSTITUCION_PAIS_ERROR = 'OBTENER_INSTITUCION_PAIS_ERROR'

export const LOAD_EDIT = 'LOAD_EDIT'
export const CLEAR_EDIT = 'CLEAR_EDIT'
export const SAVE_EDIT_EL = 'SAVE_EDIT_EL'

export const DELETE_EXPERIENCIA_LABORAL = 'DELETE_EXPERIENCIA_LABORAL'
export const LOAD_DELETE_EXPLAB = 'LOAD_DELETE_EXPLAB'
export const DELETE_EXPERIENCIA_LABORAL_ERROR =
  'DELETE_EXPERIENCIA_LABORAL_ERROR'
export const LOADOTRO = 'LOADOTRO'
export const LOADEXTRA = 'LOADEXTRA'

export const LOAD_DELETE_ESTUDIO = 'LOAD_DELETE_ESTUDIO'
export const DELETE_ESTUDIO = 'DELETE_ESTUDIO'
export const DELETE_ESTUDIO_ERROR = 'DELETE_ESTUDIO_ERROR'

export const LOAD_DELETE_CONOCIMIENTO = 'LOAD_DELETE_CONOCIMIENTO'
export const DELETE_CONOCIMIENTO = 'DELETE_CONOCIMIENTO'
export const DELETE_CONOCIMIENTO_ERROR = 'DELETE_CONOCIMIENTO_ERROR'

export const LOAD_DELETE_IDIOMA = 'LOAD_DELETE_IDIOMA'
export const DELETE_IDIOMA = 'DELETE_IDIOMA'
export const DELETE_IDIOMA_ERROR = 'DELETE_IDIOMA_ERROR'

export const LOAD_DELETE_REFLAB = 'LOAD_DELETE_REFLAB'
export const DELETE_REFLAB = 'DELETE_REFLAB'
export const DELETE_REFLAB_ERROR = 'DELETE_REFLAB_ERROR'

export const LOAD_DELETE_DOCS = 'LOAD_DELETE_DOCS'
export const DELETE_DOCS = 'DELETE_DOCS'
export const DELETE_DOCS_ERROR = 'DELETE_DOCS_ERROR'

export const LOADEXTRA_ESTUDIOS = 'LOADEXTRA_ESTUDIOS'
export const LOADEXTRA_ESTUDIOS_END = 'LOADEXTRA_ESTUDIOS_END'

export const EDIT_ESTUDIO = 'EDIT_ESTUDIO'

export const EDIT_CONOCIMIENTOS = 'EDIT_CONOCIMIENTOS'
export const LOAD_CONOCIMIENTOS = 'LOAD_CONOCIMIENTOS'
export const OBTENER_CONOCIMIENTOS = 'OBTENER_CONOCIMIENTOS'
export const SAVE_CONOCIMIENTO = 'SAVE_CONOCIMIENTO'
export const END_SAVE_CONOCIMIENTO = 'END_SAVE_CONOCIMIENTO'
export const SAVE_CONOCIMIENTO_ERROR = 'SAVE_CONOCIMIENTO_ERROR'

export const LOADEXTRA_IDIOMAS = 'LOADEXTRA_IDIOMAS'
export const LOADEXTRA_IDIOMAS_END = 'LOADEXTRA_IDIOMAS_END'

export const EDIT_IDIOMAS = 'EDIT_IDIOMAS'
export const LOAD_IDIOMAS = 'LOAD_IDIOMAS'
export const OBTENER_IDIOMAS_SAVE = 'OBTENER_IDIOMAS_SAVE'
export const SAVE_IDIOMAS = 'SAVE_IDIOMAS'
export const END_SAVE_IDIOMAS = 'END_SAVE_IDIOMAS'
export const SAVE_IDIOMAS_ERROR = 'SAVE_IDIOMAS_ERROR'

export const EDIT_REFLAB = 'EDIT_REFLAB'
export const LOAD_REFLAB = 'LOAD_REFLABS'
export const OBTENER_REFLAB_SAVE = 'OBTENER_REFLAB_SAVE'
export const SAVE_REFLAB = 'SAVE_REFLAB'
export const END_SAVE_REFLAB = 'END_SAVE_REFLAB'
export const SAVE_REFLAB_ERROR = 'SAVE_REFLAB_ERROR'

export const CARGAR_PROGRESO = 'CARGAR_PROGRESO'
export const CARGAR_PROGRESO_ERROR = 'CARGAR_PROGRESO_ERROR'

export const LOADEXTRA_ADJUNTO = 'LOADEXTRA_ADJUNTO'
export const LOADEXTRA_ADJUNTO_END = 'LOADEXTRA_ADJUNTO_END'

export const LOAD_ADJUNTO = 'LOAD_ADJUNTO'
export const OBTENER_ADJUNTO_SAVE = 'OBTENER_ADJUNTO_SAVE'
export const SAVE_ADJUNTO = 'SAVE_ADJUNTO'
export const END_SAVE_ADJUNTO = 'END_SAVE_ADJUNTO'
export const SAVE_ADJUNTO_ERROR = 'SAVE_ADJUNTO_ERROR'
